// Bilingual dictionary: English is primary, Chinese is a toggle (SPEC_web §3).
// Numbers and dates always use the en-US format and do not follow the language.
// Copy discipline: no dashes anywhere on the site, and no "·"; where a pause is
// needed use a comma, a colon or parentheses.
// Evidence wording discipline (2026-09-02 ruling): a story is only contemporaneous
// associative evidence for an unusual residual, so words that read as causal
// attribution (share, contribution, explained by, allocated) are forbidden.
export const DICT = {
  "nav.news": { en: "News", zh: "新闻" },
  "nav.fx": { en: "FX", zh: "汇率" },
  "nav.attribution": { en: "Attribution", zh: "归因" },

  "ctl.model": { en: "MODEL", zh: "模型" },
  "ctl.window": { en: "TRAINING", zh: "训练窗口" },
  "theme.light": { en: "Switch to light", zh: "切换到浅色" },
  "theme.dark": { en: "Switch to dark", zh: "切换到深色" },

  "tape.session": { en: "SESSION", zh: "交易日" },

  "pulse.label": { en: "NARRATIVE", zh: "叙事层" },
  "pulse.never": { en: "never run", zh: "从未运行" },
  "pulse.unreachable": { en: "unreachable", zh: "读不到" },
  "pulse.ok": { en: "Narrative layer ran on schedule.", zh: "叙事层按时跑过了。" },
  "pulse.age": { en: "age", zh: "距今" },
  "pulse.days": { en: "days on record", zh: "天有记录" },
  "pulse.published": { en: "Latest commentary", zh: "最近一篇短评" },
  "pulse.nonepub": { en: "none yet", zh: "尚无" },
  "pulse.pubnote": {
    en: "set by the market, not by the system, so it never changes this colour",
    zh: "由市场决定而非系统决定，不参与判色",
  },
  "pulse.thresholds": {
    en: "warn at {warn}h, red at {crit}h",
    zh: "{warn} 小时转黄，{crit} 小时转红",
  },
  "pulse.pipeline": { en: "PIPELINE", zh: "归因管线" },
  "pulse.build": { en: "PAGE BUILD", zh: "页面构建" },
  "pulse.build.label": { en: "BUILT", zh: "构建" },
  "pulse.build.tip": {
    en: "This page was built at {at}. This is the heartbeat of the publish step.",
    zh: "本页构建于 {at}。这是推送这一步的心跳。",
  },
  "pulse.build.note": {
    en: "the heartbeat of the publish step: when this page was last built",
    zh: "推送这一步的心跳：本页最近一次构建的时刻",
  },
  "pulse.build.live": {
    en: "served live by the local server; there is no build step",
    zh: "由本机服务实时供应，没有构建这一步",
  },
  "pulse.three": {
    en: "Three heartbeats, none a substitute for another: if the pipeline or the narrative layer dies, this page keeps being rebuilt on schedule; if the build dies, the other two keep looking fresh on a page nobody is refreshing.",
    zh: "三个心跳互不替代：管线或叙事层死了，本页照常按时重建；构建死了，前两个在一页没人再刷新的页面上看着永远新鲜。",
  },

  // ---------------------------------------------------------------- footer
  "foot.body": {
    en: "Personal research project, not investment advice. Narrative paragraphs are generated by a language model and checked mechanically; they may still contain errors. Data is updated once per evening; see the build time above. Data sources are listed on the",
    zh: "个人研究项目，不构成投资建议。叙事段落由语言模型生成并经机械校验，仍可能有误。数据每晚更新一次，构建时刻见页顶。数据来源见",
  },
  "foot.methodology": { en: "methodology page.", zh: "方法论页。" },

  // ------------------------------------------------------------------ News
  "news.week.title": { en: "This week's flagged days", zh: "本周的异常日" },
  "news.week.blurb": {
    en: "Days where the factor model left an unusually large residual, with the stories retrieved that day as contemporaneous evidence. Newest first.",
    zh: "因子模型残差异常放大的日子，附当天检索到的报道，作为同期关联证据，最新在前。",
  },
  "news.col.story": { en: "Story", zh: "报道" },
  "news.col.pairs": { en: "Pairs", zh: "货币对" },
  "news.col.flagged": { en: "Flagged day", zh: "异常日" },
  "news.today.title": { en: "Headlines as of {time}", zh: "头条，抓取于 {time}" },
  "news.today.plain": { en: "Headlines", zh: "头条" },
  "news.fetchedat": { en: "fetched {time}", zh: "抓取于 {time}" },
  "news.items": { en: "items", zh: "条" },
  "news.readfull": { en: "Read full story", zh: "阅读全文" },
  "news.explain": { en: "Explain", zh: "解释" },
  "news.evline": {
    en: "Flagged for {pair} on {date}",
    zh: "{date} {pair} 触发",
  },
  "news.dayres": {
    en: "{pair} residual {bp} bp (z {z})",
    zh: "{pair} 残差 {bp} bp（z {z}）",
  },
  "news.cited": { en: "CITED", zh: "已引用" },
  "news.opinions": { en: "Opinion and analysis", zh: "观点与分析" },
  "news.opinionsnote": {
    en: "Commentary, analysis, market recaps and trade views, folded away by title markers. Content-based, not source-based; display only, the narrative layer still retrieves everything.",
    zh: "按标题标记词折叠的评论、分析、行情复述与交易观点。判据按内容不按来源；只作用于展示层，叙事层照常检索全部。",
  },
  "news.nosummary": { en: "No summary was retrieved for this story.", zh: "这条报道没有取到摘要。" },
  "news.empty": {
    en: "No residual anomaly was flagged, so the narrative layer did not go looking for news.",
    zh: "没有触发残差异常，叙事层未启动检索，因此没有头条。",
  },
  "news.recent": { en: "Recent headlines", zh: "近日头条" },
  "news.earlier": { en: "Earlier this week", zh: "本周早些时候" },
  "news.earliernote": {
    en: "Headlines from earlier in the calendar week, fetched at the time shown above. Context only.",
    zh: "本日历周更早的头条，抓取时刻同上，仅作背景。",
  },
  "news.notodayyet": {
    en: "No stories dated today yet. The wires fill in as the day goes on.",
    zh: "还没有标注今天日期的报道，随时间推移会陆续出现。",
  },
  "news.alsoby": { en: "Also reported by", zh: "同题报道" },
  "news.fetchednote": {
    en: "Fetched from Google News at the time shown. Headlines appear as retrieved and carry no model judgment; flagged-day evidence lives in the list above.",
    zh: "来自 Google News，抓取时刻如上。头条按检索结果原样展示，不含模型判断；与异常残差相关的证据在上方列表。",
  },
  "news.feedfail": {
    en: "Could not reach the news feed just now.",
    zh: "暂时读不到新闻源。",
  },
  "news.week.window": {
    en: "Window {start} to {end}, the last 5 trading days",
    zh: "窗口 {start} 至 {end}，最近 5 个交易日",
  },
  "news.fallback.title": {
    en: "Latest flagged day ({date})",
    zh: "最近一次触发（{date}）",
  },
  "news.fallback.note": {
    en: "Nothing was flagged inside the current window. These stories are from the most recent flagged day, dated above, and are not part of this week.",
    zh: "本周窗口内没有触发。以下是最近一个触发日的报道，日期如上，不属于本周。",
  },
  "news.emptyweek": {
    en: "No day was flagged inside the current window.",
    zh: "本周窗口内没有触发日。",
  },
  "news.side.pairs": { en: "Daily changes, five-session charts", zh: "单日涨跌与五日走势" },
  "news.side.flagged": { en: "Flagged days", zh: "触发日" },
  "news.side.noflag": { en: "No flagged day this week.", zh: "本周没有触发日。" },
  "news.side.note": {
    en: "The residual is the part of the move the factor model does not account for. Stories are same-day evidence, nothing more; no piece of the residual is assigned to any story.",
    zh: "残差是因子模型未能解释的那部分变动。报道只是同日证据，不再把残差的任何一部分归到某条报道头上。",
  },

  // --------------------------------------------------------------- Explain
  "explain.headpair": { en: "FROM THE {pair} COMMENTARY", zh: "{pair} 短评怎么说" },
  "explain.head": { en: "FROM THE COMMENTARY", zh: "短评怎么说" },

  // -------------------------------------------------------------------- FX
  "sys": { en: "Systematic", zh: "系统性" },
  "exo": { en: "Exogenous", zh: "外生" },
  "res": { en: "Residual", zh: "残差" },
  "quote.provisional": { en: "PROVISIONAL", zh: "待确认" },
  "return.log": { en: "log return", zh: "对数收益" },
  "price.daily": { en: "1D price change", zh: "单日价格涨跌" },
  "drivers.leading": { en: "LEADING FACTORS", zh: "主要因子" },
  "drivers.empty": { en: "No nonzero factor contributions", zh: "没有非零因子贡献" },
  "residual.large": { en: "LARGE RESIDUAL", zh: "残差异常" },
  "factor.DOLLAR_LOO": { en: "Dollar basket", zh: "美元组合" },
  "factor.CARRY_LOO": { en: "Carry basket", zh: "套息组合" },
  "factor.d2Y_DIFF": { en: "Short rate spread", zh: "短端利差" },
  "factor.d10Y_DIFF": { en: "Long rate spread", zh: "长端利差" },
  "factor.dVIX": { en: "VIX change", zh: "VIX 变动" },
  "fx.stories": { en: "stories", zh: "条报道" },
  "fx.nostories": { en: "no stories", zh: "无报道" },
  "fx.storiesweek": { en: "stories on flagged days", zh: "条异常日报道" },
  "fx.newsmoving": { en: "News around {pair} flagged days", zh: "{pair} 异常日的报道" },
  "fx.nonewsforpair": {
    en: "No flagged-day story cites this pair recently.",
    zh: "近期触发日中没有报道涉及这一对。",
  },
  "fx.onmodel": { en: "on", zh: "使用" },

  "range.1d": { en: "1D", zh: "1D" },
  "range.5d": { en: "5D", zh: "5D" },
  "range.1m": { en: "1M", zh: "1M" },
  "range.6m": { en: "6M", zh: "6M" },
  "range.ytd": { en: "YTD", zh: "今年" },
  "range.1y": { en: "1Y", zh: "1Y" },
  "range.5y": { en: "5Y", zh: "5Y" },
  "range.max": { en: "MAX", zh: "全史" },
  "chart.intraday": {
    en: "Intraday prices are not collected yet. Pick 5D or wider.",
    zh: "尚未采集日内价格，请选择 5D 或更长区间。",
  },
  "chart.nocache": { en: "Price history unavailable.", zh: "价格历史不可用。" },
  "chart.short": { en: "Not enough history for this range.", zh: "该区间历史不足。" },

  "read.title": { en: "Today's read", zh: "今日总述" },
  "read.pending": { en: "AUTO SUMMARY", zh: "自动摘要" },
  "read.note": {
    en: "Calculated from saved attribution records. Open a pair to read available news notes and their sources.",
    zh: "根据已保存的归因记录汇总。展开货币对可查看已有短评与来源。",
  },
  "read.lead": {
    en: "{pair} led the session at {move}.",
    zh: "{pair} 是当日幅度最大的一对，{move}。",
  },
  "read.split": {
    en: "For {pair}, dollar and carry contribute {sys} bp, other factors {exo} bp, and the residual is {res} bp.",
    zh: "{pair} 的美元与套息贡献为 {sys} bp，其他因子贡献为 {exo} bp，残差为 {res} bp。",
  },
  "read.residual": {
    en: "{pair} has the largest absolute residual z score at {z}. Narrative review also requires a residual of at least 50 bp and an absolute z score of at least 2.",
    zh: "{pair} 的残差 z 分数绝对值最大，z = {z}。短评触发还要求残差绝对值至少 50 bp，且 z 分数绝对值至少为 2。",
  },
  "read.quiet": {
    en: "All available residual z scores are below 1.5 in absolute value.",
    zh: "当前可得的残差 z 分数绝对值均小于 1.5。",
  },
  "read.unavailable": { en: "No attribution rows for this selection.", zh: "当前选择下没有归因数据。" },

  "legend.open": { en: "What do these three mean?", zh: "这三个是什么意思？" },
  "legend.sys": {
    en: "The fitted contributions of dollar and carry, calculated from other currency pairs. A large value indicates exposure to these shared return patterns. It does not identify which country's news caused the move.",
    zh: "美元与套息因子的拟合贡献，这两个因子均由其他货币对构造。数值较大说明该货币对与这些共同收益模式的联系较强，单凭它无法判断消息来自哪个国家。",
  },
  "legend.exo": {
    en: "Fitted contributions from rate differentials, commodities, credit and equity volatility. The factor menu depends on the pair and estimator. These estimates describe statistical associations.",
    zh: "利差、商品、信用和股市波动率的拟合贡献。所用因子随货币对与估计方法变化，结果描述统计上的联系。",
  },
  "legend.window": {
    en: "How much history the regression sees. The model refits every day using only the last N trading days, roughly 3, 6, or 12 months. Short windows adapt fast but are noisy; long windows are steadier but slower to notice a regime change. 126 is the default.",
    zh: "回归能看到多长的历史。模型每天只用最近 N 个交易日重新拟合，约合 3、6、12 个月。窗口短适应快但噪声大；窗口长更稳，但对状态切换反应慢。默认 126。",
  },
  "legend.model": {
    en: "OLS fits the baseline factors. Ridge shrinks their coefficients. Lasso selects from a wider menu, then OLS refits the selected columns. Agreement means the grouped contributions are similar across these choices; it does not establish causal importance.",
    zh: "OLS 拟合基准因子，Ridge 对这些因子的系数施加收缩。Lasso 从更宽的候选集中筛选，再用 OLS 重拟合选中的列。模型间一致表示分组贡献对这几种选择较接近，不能据此认定因果重要性。",
  },
  "legend.res": {
    en: "The return left after subtracting all fitted factor contributions. When both trigger thresholds are met, the narrative layer looks for dated reporting to provide context. News coverage does not measure a headline's contribution to this residual.",
    zh: "当日收益减去全部因子贡献后剩下的部分。达到两个触发门槛后，叙事层检索有日期的报道补充背景。报道本身无法量出某条新闻对残差的贡献。",
  },

  // ----------------------------------------------------------- Attribution
  "attr.week": { en: "Week of {start} to {end}", zh: "{start} 至 {end} 当周" },
  "attr.title": { en: "Return contributions", zh: "汇率收益归因" },
  "attr.reading": { en: "Reading the figures (log-return bp)", zh: "读数说明（对数收益 bp）" },
  "bucket.systematic": { en: "Dollar and carry", zh: "美元与套息" },
  "bucket.rates": { en: "Rates", zh: "利率" },
  "bucket.risk": { en: "Risk", zh: "风险" },
  "bucket.commodities": { en: "Commodities", zh: "商品" },
  "bucket.residual": { en: "Residual", zh: "残差" },
  "attr.matrixnote": { en: "Marks identify citations. Each residual belongs to its currency and date.", zh: "勾选表示该日短评引用了报道。残差归属于货币对与日期。" },
  "attr.blurb": {
    en: "Choose a return period, then compare contributions from dollar and carry, rates, risk, and commodities. Positive and negative contributions may offset each other. Open a pair to inspect individual factors and their history.",
    zh: "选择归因期间，比较美元与套息、利率、风险和商品的贡献。正负贡献可以相互抵消。点击货币对可查看各因子及其历史。",
  },
  "attr.methodology": { en: "Methodology", zh: "方法论" },
  "attr.robust": { en: "Latest day · OLS 126", zh: "最新单日 · OLS 126" },
  "attr.dayresidual": { en: "Residual that day", zh: "当日残差" },
  "attr.restip": {
    en: "{pair} residual on {date}. It belongs to the day, not to any single story.",
    zh: "{date} {pair} 当日残差。它属于这一天，不属于任何单条报道。",
  },
  "robust.agree": { en: "SIMILAR ESTIMATES", zh: "估计结果接近" },
  "robust.ridge": { en: "RIDGE DIVERGES", zh: "RIDGE 偏离" },
  "robust.lasso": { en: "LASSO RESELECTS", zh: "LASSO 换因子" },
  "robust.abstain": { en: "LASSO ABSTAINS", zh: "LASSO 弃权" },
  "robust.tip": {
    en: "Latest daily comparison against OLS 126: Ridge {r}, post-Lasso {l}, in units of a typical residual. Similar estimates can still leave a large residual.",
    zh: "最新单日与 126 日 OLS 的比较：Ridge {r}，post-Lasso {l}，单位为一个典型残差。结果接近时仍可能存在较大残差。",
  },
  "attr.pair": { en: "Pair", zh: "货币对" },
  "attr.move": { en: "Move", zh: "变动" },
  "attr.decomp": { en: "Decomposition (bp)", zh: "分解（bp）" },
  "attr.matrix": { en: "Stories cited on flagged days", zh: "触发日引用的报道" },
  "attr.nomatrix": {
    en: "No flagged day on record yet.",
    zh: "还没有触发日记录。",
  },

  "loading": { en: "Loading", zh: "加载中" },
  "fx.absolute": { en: "Percentages show each group's absolute size divided by the sum of the three absolute sizes.", zh: "百分比为该组贡献绝对值除以三组绝对值之和。" },
  "fx.fit": { en: "Training R²", zh: "训练窗口 R²" },
  "research.open": { en: "Factors and sensitivity history", zh: "因子贡献与敏感度历史" },
  "attr.period": { en: "{start} to {end}", zh: "{start} 至 {end}" },
  "attr.horizon": { en: "RETURN PERIOD", zh: "归因期间" },
  "period.1": { en: "1 day", zh: "1 日" },
  "period.5": { en: "5 days", zh: "5 日" },
  "period.21": { en: "21 days", zh: "21 日" },
  "attr.basis": { en: "Periods count trading observations. Window sets the training history. Robustness badges refer to the latest daily OLS 126 comparison.", zh: "归因期间按交易观测计数，窗口设置用于拟合的历史长度。稳健性徽标对应最新单日的 126 日 OLS 比较。" },
  "attr.provisional": { en: "This period includes provisional observations.", zh: "本期间包含待确认观测。" },
  "error": { en: "Could not reach the server.", zh: "无法连接服务。" },
};

let lang = localStorage.getItem("fxdash.lang") || "en";

export function getLang() { return lang; }

export function setLang(next) {
  lang = next === "zh" ? "zh" : "en";
  try { localStorage.setItem("fxdash.lang", lang); } catch (e) { /* private mode */ }
  document.documentElement.lang = lang === "zh" ? "zh" : "en";
}

export function t(key, vars) {
  const entry = DICT[key];
  let text = entry ? (entry[lang] || entry.en) : key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) text = text.split("{" + k + "}").join(v);
  }
  return text;
}
